[workspace]
members = ["hala-tunnel", "hala-tunnel-quic"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/quictun.git"
version = "0.1.2"

[workspace.dependencies]
anyhow = "^1"
bencher = "^0.1.5"
clap = "^4.4"
core2 = "^0.4.0"
futures = "^0.3.29"
futures-test = "^0.3"
log = "^0.4"
pretty_env_logger = "^0.5"
quiche = "^0.19.0"
rand = "^0.8"
thiserror-no-std = "^2.0"
