[workspace]
members = ["hala-mux", "hala-quic", "hala-quic-tunnel"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/quictun.git"
version = "0.1.2"

[workspace.dependencies]
anyhow = "^1"
bencher = "^0.1.5"
bytes = "^1.5.0"
clap = {version = "^4.4", features = ["derive"]}
core2 = "^0.4.0"
futures = "^0.3.29"
futures-test = "^0.3"
log = "^0.4"
mio = {version = "^0.8.9", features = ["os-poll", "net"]}
pretty_env_logger = "^0.5"
quiche = "^0.19.0"
rand = {version = "^0.8", features = ["getrandom"]}
thiserror-no-std = "^2.0"
