[workspace]
members = ["hala-mux", "hala-io-driver"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/HalaOS/quictun.git"
version = "0.1.2"

[workspace.dependencies]
anyhow = "^1"
async-recursion = "1.0.5"
bitmask-enum = "2.2.3"
bytes = "^1.5"
clap = {version = "^4.4", features = ["derive"]}
core2 = "^0.4.0"
divan = "^0.1"
futures = {version = "^0.3.29", features = ["executor", "thread-pool"]}
futures-test = "^0.3"
log = "^0.4"
mio = {version = "^0.8.9", features = ["os-poll", "net"]}
pretty_env_logger = "^0.5"
quiche = "^0.19.0"
rand = {version = "^0.8", features = ["getrandom"]}
serde = {version = "^1.0", features = ["derive"]}
serde_json = {version = "^1.0"}
thiserror = "^1.0.50"
thiserror-no-std = "^2.0"

hala-io-context = {path = "./hala-io-context", default = false, version = "^0.1"}
hala-io-test = {path = "./hala-io-test", default = false, version = "^0.1"}
hala-mux = {path = "./hala-mux", version = "^0.1"}
hala-net = {path = "./hala-net", default = false, version = "^0.1"}
