[package]
description = "A type to batch poll same type of futures"
documentation = "https://docs.rs/batch-poll"
edition.workspace = true
license = "MIT"
name = "batch-poll"
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcar = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
