[package]
description = "Hala io reactor framework"
edition.workspace = true
name = "hala-io-driver"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask-enum = {workspace = true}
futures = {workspace = true, optional = true}
log = {workspace = true}
mio = {workspace = true, optional = true}

[dev-dependencies]
divan = {workspace = true}
pretty_env_logger = {workspace = true}

[features]
default = ["mio_driver", "notifier"]
mio_driver = ["mio"]
notifier = ["futures"]

[[bench]]
harness = false
name = "typed_handle"

[[bench]]
harness = false
name = "driver"
