[package]
description = "Hala io reactor framework"
edition.workspace = true
name = "hala-io-driver"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask-enum = {workspace = true}
divan = {workspace = true}
log = {workspace = true}

[dev-dependencies]
pretty_env_logger = {workspace = true}
