[package]
description = "Hala io reactor framework"
edition.workspace = true
name = "hala-io-driver"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = {workspace = true}
divan = {workspace = true}
futures = {workspace = true}
log = {workspace = true}
mio = {workspace = true}
rand = {workspace = true}

[[bench]]
harness = false
name = "vtable"
