[package]
description = "Hala network framework"
edition.workspace = true
name = "hala-net"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
hala-io-test = {workspace = true, optional = true}
hala-reactor = {workspace = true, optional = true}
log = {workspace = true}
mio = {workspace = true}
rand = {workspace = true}

[dev-dependencies]
divan = {workspace = true}
pretty_env_logger = {workspace = true}

[features]
default = []
mt = ["hala-reactor/mt"]
st = ["hala-reactor/st"]
test-mt = ["hala-reactor/mt", "hala-io-test/mt"]
test-st = ["hala-reactor/st", "hala-io-test/st"]

[[bench]]
harness = false
name = "udp_group"
