[package]
description = "Hala network framework"
edition.workspace = true
name = "hala-net"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
hala-io-test = {workspace = true, optional = true}
hala-reactor = {workspace = true, optional = true}
log = {workspace = true}
mio = {workspace = true}
pretty_env_logger = {workspace = true}
rand = {workspace = true}

[features]
default = ["mt"]
mt = ["hala-reactor/mt"]
mt-test = ["hala-reactor/mt", "hala-io-test/mt"]
st = ["hala-reactor/st"]
st-test = ["hala-reactor/st", "hala-io-test/st"]
