[package]
description = "Hala network framework"
edition.workspace = true
name = "hala-net"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = {workspace = true}
hala-reactor = {workspace = true}
mio = {workspace = true}
