[tasks.test-all]
dependencies = ["test-mt", "test-st"]

[tasks.test-mt]
args = ["test", "--no-default-features", "--features", "test-mt"]
command = "cargo"

[tasks.test-st]
args = ["test", "--no-default-features", "--features", "test-st"]
command = "cargo"
