[package]
description = "Hala asynchronous socket implementation"
edition.workspace = true
name = "hala-socket"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core2 = {workspace = true}
futures = {workspace = true, optional = true}
mio = {workspace = true}
thiserror = {workspace = true}

[features]
default = ["multi-thread"]
multi-thread = []
tester = ["futures"]
