[package]
description = "Hashed timewheel implementation"
documentation = "https://docs.rs/timewheel"
edition.workspace = true
license = "MIT"
name = "hashed-timer"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcar = {workspace = true}
dashmap = {workspace = true}
