[package]
description = "A collection of types and traits for handle Rust mutable reference in single thread / multithread modal"
documentation = "https://docs.rs/shared"
edition.workspace = true
license = "MIT"
name = "shared"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {workspace = true}

[dev-dependencies]
divan = {workspace = true}
futures = {workspace = true}
futures-test = {workspace = true}
log = {workspace = true}
pretty_env_logger = {workspace = true}
