[package]
description = "A type to batch poll same type of futures"
documentation = "https://docs.rs/batching"
edition.workspace = true
license = "MIT"
name = "batching"
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boxcar = {workspace = true}
cooked-waker = {workspace = true}
dashmap = {workspace = true}
futures = {workspace = true}
futures-test = {workspace = true}
lockfree-rs = {workspace = true}
log = {workspace = true}

[dev-dependencies]
pretty_env_logger = {workspace = true}
