[package]
description = "Hala asynchronous io test proc-macro toolkit"
documentation = "https://docs.rs/hala-io-test-derive"
edition.workspace = true
license = "MIT"
name = "hala-io-test-derive"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "^1.0"
syn = {version = "^2.0", features = ["full"]}

[lib]
proc-macro = true
